name: build

on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ut:
    runs-on: macOS-latest
    steps:
      - uses: actions-hub/docker/cli@master

      - name: install httpbin
        run: |
          docker pull kennethreitz/httpbin
          docker run -p 80:80 kennethreitz/httpbin

      - uses: actions/checkout@master

      - name: install cocoapods
        run: gem install cocoapods

      - name: install dependencies
        run: |
          cd Example
          pod install
        shell: bash
        
      - name: run test
        run: xcodebuild test -workspace ./Example/YMHTTP.xcworkspace -scheme 'YMHTTP-Example' -destination 'platform=iOS Simulator,name=iPhone 11'
        shell: bash
